### ISSUE TITLE
Support for hexadecimal strings

### ISSUE THREAD

**Issue by Jlll1** [chrisbra/Colorizer#101]
Many applications require use of hexadecimal representation for colors (for example `0x0000aa`). 
Currently Colorizer does not highlight these. This feature request is about adding support for hexadecimal color representation and highlighting them as well.
Example:
![image](https://user-images.githubusercontent.com/71319302/210910603-cf5607ce-ece3-4e9e-a6ec-900a9f75d443.png).

**Comment by chrisbra** [comment]
please see the help page:

https://github.com/chrisbra/Colorizer/blob/715c91303f0f7a59b21af39c9d168d975ca2c831/doc/Colorizer.txt#L220-L241
