### ISSUE TITLE
Some error occurred here:  Colorize in vim file

### ISSUE THREAD

**Issue by CampbellCrowley** [chrisbra/Colorizer#102]
Hi I'm having this issue while trying to colorize what seems to be any `ctermfg` or `ctermbg` colors:
```
Colorizer: Some error occurred here:  Colorize: ['\%(gui[fb]g\|cterm[fb]g\)\s*=\s*\<\%(\d\+\|#\x\{6}\|\w\+\)\>', function('<SNR>208_PreviewVimColors'), 'colorizer_vimcolors', '&ft ==# "vim"', []]
Colorizer: Position: [0, 1, 11, 0]
```
This is the minimal example I used to reproduce:
```
hi Normal ctermfg=#000000
```
![image](https://github.com/chrisbra/Colorizer/assets/17092608/1e4d8841-473e-48e8-9b2e-56db935268c6)

And my Vim version on Ubuntu 22.04:
```
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled May 18 2023 11:54:22)
Included patches: 1-1565
```

It seems to work great in all my other use-cases. Any idea what's going wrong?
This seems to be similar to #97 , but I'm not sure how that got resolved.

**Comment by chrisbra** [comment]
Wow, I broke my own plugin with https://github.com/vim/vim/commit/360da40b47a84ee8586c3b5d062f8c64a2ac9cc6 
Let me check in more detail, why this breaks. I am currious.
