### ISSUE TITLE
highlighting hex colour: delimiter

### ISSUE THREAD

**Issue by teschmitz** [chrisbra/Colorizer#13]
I am using your plugin in a config file and I note that dash and underscore are not recognized as delimiters for hex colours (#rrggbb or #rgb)

Therefore, the following occurrences are not highlighted:
# A0A0A0-
# A0A0A0_

**Comment by omeid** [comment]
#RRGGBBAA is now supported in Chrome, Firefox, Android, and React Native. Would be great to have support for it!

**Comment by chrisbra** [comment]
What does the AA stand for? Do we need to calculate anything for that?

**Comment by omeid** [comment]
[Alpha](https://developer.mozilla.org/en/docs/Web/CSS/color_value#rgba()) :)

**Comment by chrisbra** [comment]
Can you please check latest commit?

**Comment by omeid** [comment]
Well do later today. Thanks for looking into this!

**Comment by omeid** [comment]
Works great. Thanks!
