### ISSUE TITLE
Error 119 after latest update

### ISSUE THREAD

**Issue by easysid** [chrisbra/Colorizer#40]
Hi, I use this plugin to highlight colors in my xresources files. Since the last update, I see the following error continuously while editing files, if :ColorHighlight/Toggle is turned on
> Error detected while processing CursorMovedI Auto commands for "\<buffer=*[some number]*>":
> E119: Not enough arguments for function: Colorizer#ColorLine

I never have had this error before.
Thanks.

*EDIT*: 
Error also presents in css files.
It occurs in normal mode as well, with the message displaying *CursorMoved* instead of *CursorMovedI*

**Comment by chrisbra** [comment]
Hi easysid!

On Mo, 26 Jan 2015, easysid wrote:

> Hi, I use this plugin to highlight colors in my xresources files. Since the last update, I see the following error continuously while editing files, if :ColorHighlight/Toggle is turned on
> > Error detected while processing CursorMovedI Auto commands for "\<buffer=*[some number]*>":
> > E119: Not enough arguments for function: Colorizer#ColorLine
> 
> I never have had this error before.

Sorry for breaking this. I've fixed it now.

Best,
Christian
-- 
Image ist das, was man braucht, wenn man für andere so aussehen will,
wie man gerne wär.
		-- Erwin Pelzig
