### ISSUE TITLE
Colorizer#ColorOff disables syntax highlighting

### ISSUE THREAD

**Issue by audriusk** [chrisbra/Colorizer#41]
Commit 3a5b2cb introduced `syn clear` inside Colorizer#ColorOff function, which disables syntax highlighting for current buffer. Before this change Colorizer#ColorOff only turned off color highlighting.

**Comment by chrisbra** [comment]
Thanks for reporting. I think I have fixed it.

**Comment by audriusk** [comment]
Syntax highlighting stays intact now, but I'm getting this error message:
> No such highlight group name: ColorTermESC

**Comment by chrisbra** [comment]
Oops, sorry. Fixed that.

**Comment by audriusk** [comment]
Working fine now, thanks!
