### ISSUE TITLE
3ac2e7 breaks coloring in neovim

### ISSUE THREAD

**Issue by sencer** [chrisbra/Colorizer#44]
The commit for basic neovim support, 3ac2e7, actually results in not coloring at all in neovim, in my case.  I can revert to previous commit, to make it work again -although without true color support.

**Comment by chrisbra** [comment]
So reverting it, will enable the plugin again for neovim?

**Comment by sencer** [comment]
Yes, it would. I don't understand the problem though.

**Comment by chrisbra** [comment]
Do you know, if there is a way, to detect if neovim is running in true color support?

**Comment by sencer** [comment]
I am not sure if this is what you are asking, but one should set environment variable `NVIM_TUI_ENABLE_TRUE_COLOR=1` for the true color support.

**Comment by sencer** [comment]
Actually, sorry for stealing your time: I found it was a problem with my configuration, which overrides `NVIM_TUI_ENABLE_TRUE_COLOR=1`. Still, you might want to check if this is set though. Best!

**Comment by chrisbra** [comment]
thanks. I have pushed a fix, that should make it work with true colors in the terminal.
