### ISSUE TITLE
Stopped working in neovim (0.1.4)

### ISSUE THREAD

**Issue by chapati23** [chrisbra/Colorizer#46]
hey :)

i've been refactoring my vim setup and noticed that for quite some time colorizer wasn't working anymore. i'm on the most recent nvim, tried with a stripped down setup with removing all other plugins and just keeping colorizer: still not working.

also not getting any errors so kinda lost on how to debug. any pointers?

:ColorHighlight does nothing for me (also no error)

I've read that it could have something to do with true-color env settings.
also tried `let $NVIM_TUI_ENABLE_TRUE_COLOR=1` on the bottom of my init.vim with no luck

**Comment by chrisbra** [comment]
Hi chapati!

On Di, 10 Mai 2016, chapati wrote:

> hey :)
> 
> i've been refactoring my vim setup and noticed that for quite some time colorizer wasn't working anymore. i'm on the most recent nvim, tried with a stripped down setup with removing all other plugins and just keeping colorizer: still not working.
> 
> also not getting any errors so kinda lost on how to debug. any pointers?
> 
> :ColorHighlight does nothing for me (also no error)
> 
> I've read that it could have something to do with true-color env settings.
> also tried `let $NVIM_TUI_ENABLE_TRUE_COLOR=1` on the bottom of my init.vim with no luck
> 

So you are not using true color mode usually? Hm, I wonder why it 
doesn't work. I guess I'll have to find a neovim backport


-- 
Was die neuen Unwissenden holen müssen:
Fertigfugen

**Comment by chapati23** [comment]
confirmed. thanks for the quick fix!
