### ISSUE TITLE
Missing concealment support for `$(tput sgr0)`

### ISSUE THREAD

**Issue by LucHermitte** [chrisbra/Colorizer#53]
Hi,

First, thanks for the plugin!

I've noticed a little issue with the codes used to clear highlighting on my console that are produced with `$(tput sgr0)`. While they seem to be correctly processed to reset the highlighting, they aren't concealed.
Note: In my log file they appear as `^[(B^[[m` (where `^[` is the usual escape sequence).

The typical bash sequence that can reproduce the issue is:

```bash
declare -A colors=([reset]="$(tput sgr0)" [red]="$(tput setaf 1)")
echo "foo${colors[red]}bar${colors[reset]}42" > some.log
gvim -c ':ColorToggle' some.log
```

**Comment by chrisbra** [comment]
Interesting, for me `tput sgr0` returns `^[[m^O`, ah well, let's just both hide.

**Comment by LucHermitte** [comment]
Thank you Christian!
