### ISSUE TITLE
MacVim/iTerm: no highlighting

### ISSUE THREAD

**Issue by osenvosem** [chrisbra/Colorizer#54]
Checked in MacVim 8.0.771 (135) and iTerm + VIM 8.0.844

Plugin is loaded.
![2](https://user-images.githubusercontent.com/6762673/29009509-851fb56a-7b2c-11e7-85f1-8e4bc020ae3b.jpg)

But nothing is happening.
![1](https://user-images.githubusercontent.com/6762673/29009474-4463c9a8-7b2c-11e7-9a3f-c7bf1fd70a70.jpg)

**Comment by chrisbra** [comment]
what did you do?

**Comment by osenvosem** [comment]
@chrisbra installed and relaunched vim.

**Comment by chrisbra** [comment]
that is not how it works. Did you even had a look at the help?

**Comment by osenvosem** [comment]
@chrisbra I'm sorry for my inattention. 🙂
Thank you for the plugin. Nice job! 👍
