### ISSUE TITLE
Incorrect colors displaying

### ISSUE THREAD

**Issue by boardfish** [chrisbra/Colorizer#57]
I'm trying to port the base16-google themes to my wal wallpapers, and I'm using Colorizer as a guide to which slots I've put each color in. However, despite having set xterm-256color and setting t_Co to 256,
 the colors are still highlighted inaccurately. I can't really see another way to pinpoint the problem.

![](https://user-images.githubusercontent.com/20680337/29816447-f74d6692-8cab-11e7-8ab4-fb1661ce07c6.png)

EDIT: Getting this in other terminals too, with other colorizer plugins. It's clear that it perhaps doesn't have much to do with this program at all. I'll post a solution here when I find one.

**Comment by chrisbra** [comment]
Okay good. BTW: I don't understand from your screenshot what exactly is wrong with the colors.
