### ISSUE TITLE
Add ANSI escape sequences support

### ISSUE THREAD

**Issue by tterranigma** [chrisbra/Colorizer#62]
They are described [here](https://unix.stackexchange.com/questions/124407/what-color-codes-can-i-use-in-my-ps1-prompt). 

Would it be possible to add support for them so that eg [this file](https://github.com/niieani/bash-oo-framework/blob/master/lib/UI/Color.var.sh) shows colored?

**Comment by chrisbra** [comment]
Colorizer already has ANSI escape sequence support. Have you tried it?

**Comment by tterranigma** [comment]
Hello!

I guess, on eg this line:

```
UI_Color_Blue=$'\033[0;34m'
```

`\033[0;34m` could be shown in blue.

**Comment by chrisbra** [comment]
okay, should work now

**Comment by tterranigma** [comment]
Yes, thanks!
