### ISSUE TITLE
Highlighting hex colors that have a different prefix

### ISSUE THREAD

**Issue by mklein994** [chrisbra/Colorizer#63]
I would like to highlight `0xffaa33` the same way as `#ffaa33`. I'm using Neovim.

Here is a minimal `init.vim` to reproduce the problem:

```nvim
" ~/min-init.vim

let g:colorizer_hex_pattern = ['0x', '\x\{6}', '']

call plug#begin($HOME.'/.local/share/nvim/plugged')
Plug 'chrisbra/Colorizer'
call plug#end()

" 0xffaa33
```

Using this configuration, the comment at the end of the file should be highlighted in an orange color (`#ffaa33`), but isn't:

```sh
nvim -u NONE -u ~/min-init.vim -c ':ColorHighlight' min-init.vim
```

I tried a few things, and noticed that both of the bottom comments are highlighted as long as the colors are the same, using this configuration:

```nvim
" ~/min-init.vim

let g:colorizer_hex_pattern = ['\%(0x\|#\)', '\x\{6}', '']

call plug#begin($HOME.'/.local/share/nvim/plugged')
Plug 'chrisbra/Colorizer'
call plug#end()

" 0xffaa33
" #ffaa33
```

**Comment by chrisbra** [comment]
thanks for the clear example. I think I fixed it
