### ISSUE TITLE
ANSI sequences not fully escaped in gVim.

### ISSUE THREAD

**Issue by koblihh** [chrisbra/Colorizer#66]
Hi Christian,

I am having trouble understanding how to properly debug the incorrectly escaped ANSI sequences via `Colorizer`. I would greatly appreciate it if you could give some pointers on a possible way of resolving the issue.

See the attached pics below for your reference.

`Before:`
![before](https://user-images.githubusercontent.com/13987638/50008616-0a31cf00-ffb5-11e8-8fca-ac1fd6750e56.png)
`After:`
![after](https://user-images.githubusercontent.com/13987638/50008656-2e8dab80-ffb5-11e8-918d-cf9519ccc65d.png)
`Expected:`
![expected](https://user-images.githubusercontent.com/13987638/50008664-364d5000-ffb5-11e8-941b-d22d8907f8cc.png)

I am currently using `gvim_8.1.0095_x64` on `Windows 7`.

Kind regards,
K.

**Comment by chrisbra** [comment]
hm, currently, it expects an `^O` following the `^[[m` to hide it. I made it optional.
