### ISSUE TITLE
can't get it to highlight terminal escape sequences

### ISSUE THREAD

**Issue by mkoura** [chrisbra/Colorizer#69]
Highlighting works for e.g. css files, but I cant get it to work with escape sequences.
E.g. the example with `r! ls -la --color` and then `ColorHighlight` does nothing, `echo &t_Co ` returns 256, `echo getmatches()` returns empty result.

How to debug what's wrong?

**Comment by chrisbra** [comment]
Ah, it looks like 160ce308b7e7619ce2517e955 broke it. Let me fix this (and make sure to use `:ColorHighlight` in a buffer with `text` or empty filetype).

**Comment by mkoura** [comment]
Thanks for quick response, works now!
