### ISSUE TITLE
Problem with :ColorHighlight sometimes

### ISSUE THREAD

**Issue by mckellyln** [chrisbra/Colorizer#72]
Colorizer: Some error occured here:  Colorize: ['\%(gui[fb]g\|cterm[fb]g\)\s*=\s*\<\%(\d\+\|#\x\{6}\|\w\+\)\>', function('<SNR>47_PreviewVimColors'), 'colorizer_vimcolors', '&ft ==# "vim"', []]
Colorizer: Position: [0, 2015, 29, 0]

**Comment by mckellyln** [comment]
I can work around this with:
```
let g:colorizer_vimcolors_disable = 1
```
But let me know if there is anything I can do to help debug/solve.

**Comment by chrisbra** [comment]
So what is so special at that line 2015?

**Comment by mckellyln** [comment]
Nothing that I can see -
```
2015   elseif &filetype !=# 'GV'
```

**Comment by chrisbra** [comment]
that does not match `\%(gui[fb]g\|cterm[fb]g\)\s*=\s*\<\%(\d\+\|#\x\{6}\|\w\+\)\>`, so how does it interfere with Colorizer? Can you provide the complete file (or a stripped down example)?

**Comment by mckellyln** [comment]
@chrisbra I'll work on debugging this.  If I can come up with something that reliable shows a problem I'll re-open and post.  Thanks for this.
