### ISSUE TITLE
Bold ANSI code not supported

### ISSUE THREAD

**Issue by daveyarwood** [chrisbra/Colorizer#76]
I'm evaluating Colorizer to see if it can interpret ANSI escape codes in a Clojure REPL buffer, and I'm thrilled to see that it works for the most part! One thing I noticed is that the `\e[1m` (bold) escape code doesn't appear to be working. See my screenshots in https://github.com/Olical/conjure/issues/53#issuecomment-552614727 (that post and the one above it) for context.

Here are a couple more screenshots, with and without colorizer enabled, so you can see the ANSI codes:

![2019-11-11-162458_921x164_scrot](https://user-images.githubusercontent.com/4909079/68622570-6e4c6400-04a0-11ea-9f7f-169ad4265916.png)

![2019-11-11-162509_914x163_scrot](https://user-images.githubusercontent.com/4909079/68622571-6e4c6400-04a0-11ea-9c7e-c9970ab14f6b.png)

One thing that's interesting is that Vim prints a grayed-out `^[` where we would expect the escape character `\e`:

```
^[[1mExecuting:  ^[[1mtesting bold^[[1m...^[[0m
```

I think this is actually:

```
\e[1mExecuting:  \e[1mtesting bold\e[1m...\e[0m
```

which you can paste into your terminal (`echo -e '\e[1mExecuting:  \e[1mtesting bold\e[1m...\e[0m'
Executing:  testing bold...`) and see that it's bold.

Great work on Colorizer, let me know if I can help with this in some way!

**Comment by chrisbra** [comment]
I believe bold isn't actually supported in a terminal.

**Comment by daveyarwood** [comment]
I don't follow what you mean.

![2019-11-15-100614_461x112_scrot](https://user-images.githubusercontent.com/4909079/68953298-9c2af480-078f-11ea-964c-0d07839aa90c.png)

**Comment by chrisbra** [comment]
Yes, but highlighting highlighting in vim so not support that

**Comment by daveyarwood** [comment]
Surely it's possible? I'm not sure what is enabling this functionality, but whenever I write comments that contain words like TODO, or FIXME, Vim makes them bold:

![2019-11-15-144546_267x81_scrot](https://user-images.githubusercontent.com/4909079/68971033-a14f6a00-07b6-11ea-821b-9d1fc6189832.png)

(I also have Vim setup to make comments italic -- you can ignore that part)

**Comment by chrisbra** [comment]
Hmm indeed, will investigate

**Comment by chrisbra** [comment]
I had some look, but this would involve getting the syntax element at the current cursor position and add the bold attribute to it. I don't think this is worth it.

**Comment by chrisbra** [comment]
should be there now
