### ISSUE TITLE
Text doesn't consistently colorize or stay colorized

### ISSUE THREAD

**Issue by daveyarwood** [chrisbra/Colorizer#77]
I'm using [Conjure](https://github.com/Olical/conjure) for Clojure development. It basically gives you a Clojure REPL integrated into Neovim, with a log buffer (`ft=clojure`) where output is displayed.

I have a project that prints text to stdout that contains ANSI color codes. My goal is to render the text in color in the Conjure log buffer.

With this configuration:

```viml
" I was hoping that this would enable colorizer for every filetype, but I still
" had to run :ColorHighlight (or :ColorToggle) manually even after adding this.
let g:colorizer_auto_color = 1

" Clojure is included here because colorizer interprets ANSI escape codes, and I
" use Conjure, which has a log buffer whose filetype is Clojure. Conjure +
" colorizer = awesome colored text output on stdout/stderr!
let g:colorizer_auto_filetype='scss,css,clojure'
```

I see this behavior:

https://daveyarwood.keybase.pub/misc/201911141433-conjure-colorizer.gif

The issues I'm noticing are:

* The Conjure buffer isn't colorizing on first view.
* Sometimes it colorizes or decolorizes when I'm just moving back and forth between the splits.
* I can run `:ColorHighlight` to manually colorize it, but then it decolorizes when I move away to another split.

**Comment by daveyarwood** [comment]
I've partially worked around the problem by adding this autocmd to my vimrc:

```viml
autocmd BufEnter,BufLeave /tmp/conjure.cljc ColorHighlight
```

It's still a little bit flaky, as you can see in this new gif:

https://daveyarwood.keybase.pub/misc/201911141526-conjure-colorizer.gif

I still have to enter the buffer in order to get color. What I want is for that buffer to be colorized when it gets created and then I want it to stay colorized even if I move away into another split.

**Comment by chrisbra** [comment]
hm, is that specific to a terminal buffer?

**Comment by daveyarwood** [comment]
It's not a terminal buffer, it's a file `/tmp/conjure.cljc` (filetype: `clojure`)

**Comment by Olical** [comment]
The Conjure log is a regular old buffer, a few options get set upon creation though:

https://github.com/Olical/conjure/blob/52618ff54b164b648e2f84fd5e83fa8f81e23f3e/lua/conjure.lua#L71-L83

**Comment by chrisbra** [comment]
I don't see why it shouldn't work. Is there an easy way to reproduce? Perhaps share a view or session file?

**Comment by daveyarwood** [comment]
I came up with a simpler repro: 

https://daveyarwood.keybase.pub/misc/201911151455-colorizer-splits.gif

In this gif, I'm not using Conjure, I'm just editing a tiny CSS file and opening the same file in splits.

It appears that Colorizer is only colorizing the buffer that's in focus.

**Comment by otreblan** [comment]
I'm having a similar error, but with [vim-dispatch](https://github.com/tpope/vim-dispatch) and cmake.
And quickfix.

**Comment by daveyarwood** [comment]
I tried a bunch of other autocmds and got a little bit further. Here's where I'm at now:

```viml
augroup auto_colorize
  autocmd!
  autocmd
        \ BufNewFile,BufRead,BufEnter,BufLeave,WinEnter,WinLeave,WinNew
        \ /tmp/conjure.cljc,*.css,*.scss
        \ ColorHighlight
augroup END
```

Adding WinEnter, WinLeave and WinNew seems to improve the behavior such that when I open a new split, it's colorized, (it still loses color when I make a change in one split of the same file, like in my gif above), and when I move between splits, the splits that lost color get colorized again.

It still seems like the behavior we're missing is that whenever you change text, it should re-colorize all the buffers/windows. I attempted to get this behavior by adding TextChanged and TextChangedI to the autocmd, but that didn't work.

**Comment by daveyarwood** [comment]
NB: With the above in place, I was able to comment out the following options because they make no difference in behavior:

```viml
" let g:colorizer_auto_color = 1
" let g:colorizer_auto_filetype='scss,css,clojure'
```

**Comment by daveyarwood** [comment]
I just discovered that Colorizer has an option to disable its default behavior where it de-colorizes whenever you leave a buffer. This gets me most of the way to fixing this issue:

```viml
let g:colorizer_auto_color = 1
let g:colorizer_auto_filetype='scss,css,clojure'
let g:colorizer_disable_bufleave = 1
```

The remaining issues I'm seeing are:

1. Floating windows are not automatically colorized.
2. Occasionally I see that certain lines / columns seem to be "stained" a certain color, perhaps as a relic of having colorized a different buffer:

![2020-05-20-110914_802x369_scrot](https://user-images.githubusercontent.com/4909079/82463891-67c02a00-9a8b-11ea-9f8e-6496a65b780d.png)

**Comment by her** [comment]
Thanks for the comments everyone, I too noticed that 

```vim
let g:colorizer_auto_color = 1
let g:colorizer_auto_filetype='scss,css,js'
let g:colorizer_disable_bufleave = 1
```

made no effect. _unless_ I sourced my .vimrc in a loaded buffer `:so $MYVIMRC`, which makes me think that it could be an initialization problem with this plugin. It's just not sourcing these at the right time.

In any case, this works for me:

```
augroup auto_colorize
  autocmd!
  autocmd
        \ BufNewFile,BufRead,BufEnter,BufLeave,WinEnter,WinLeave,WinNew
        \ *.js,*.css,*.scss,*.sass
        \ ColorHighlight
augroup END
```

So I'll run with this for now and if I get some free time maybe look at the code here.

**Comment by Cris-lml007** [comment]
I think a better direction to get it activated in a summary is:  
`autocmd FileType * : ColorHighlight`
with that the colors for all languages would be activated

**Comment by chrisbra** [comment]
would you please create a PR with a doc improvement for this please?

**Comment by Cris-lml007** [comment]
I don't think it's convenient to modify or implement the command that mentions the script, since this makes vim slow down a bit, but if you want the plugin to be initialized when opening a file no matter that vim slows down, you can add the command mentioned above in .vimrc.
`autocmd FileType * : ColorHighlight`

**Comment by chrisbra** [comment]
let me add this to the documentation at least
