### ISSUE TITLE
Coloring ANSI coded text should hide the ANSI code

### ISSUE THREAD

**Issue by lucasbretana** [chrisbra/Colorizer#80]
Hi, first and foremost thanks for the plugin :)

Now, I has viming some log file that contains ANSI codes for colors to be interpreted and properly colorized on some application, e.g. the shell interpreter
As the .gif in the README.md display, once you turn on the :ColorHighlight two things should happen:
1. colors 🙃 (which works fine) 
2. the ANSI code should be hidden, but that isn't working.. 😞 
What happens is that color is displayed all right, but also colors the ANSI code..

Seems like something simple to be fixed, but I have no experience with vim scripting, so didn't even try to fixed it myself.. 😅 

![Demonstrative image](https://user-images.githubusercontent.com/7704537/74947030-fd8ae100-53d8-11ea-8d6a-c34bbe24c244.png)

**Comment by chrisbra** [comment]
do you have concealing turned on? Try `:set conceallevel=2 concealcursor=nv`

**Comment by lucasbretana** [comment]
Thanks for quick response

No, I did not have it, took me a few minutes to decide what new vim to install, finally I decided to do a long time coming task to compile it myself, making sure +conceal was enabled

Thanks 😄
