### ISSUE TITLE
Colorizer: Some error occured here:  ColorTerm

### ISSUE THREAD

**Issue by atsaloli** [chrisbra/Colorizer#86]
Hello,

I just installed Colorizer because I would like to render escape codes in Vim.

I ran `:.,$ ! mdless /some/markdown/file.md` to convert a Markdown file to Text using [mdless](https://github.com/ttscoff/mdless) but I got the error:

```
Colorizer: Some error occured here:  ColorTerm
```

So, for now, I'm using `mdless --no-color` but I'd really like to be able to display colors in my Vim session because I'm teaching a course inside Vim, my source material is in Markdown, and I would like to render each file as it comes up.  

How do I troubleshoot an error like this, please?

**Comment by chrisbra** [comment]
so what does the resulting file look like? Note that highlighting ANSI escape sequences is a bit brittle.

**Comment by atsaloli** [comment]
Thanks for the quick response, Christian, much appreciated.

As I recall, the resulting file looks no different -- still shows the ANSI escape codes in the vim window rather than rendering them (I can see [ ; and the other characters).

Thanks for letting me know that highlighting ANSI escape sequences is brittle. I've found I can use [mdless](https://github.com/ttscoff/mdless/) instead to accomplish my aim.

I'm all set.  Thank you very much for your help!

Best,
Aleksey
