### ISSUE TITLE
Recognise variable references in *.vim themes

### ISSUE THREAD

**Issue by savchenko** [chrisbra/Colorizer#92]
Hopefully this is "easier" to implement for `.vim` rather than for other formats. On the screenshot below hex colours are rendered as expected, however the `g:terminal_color_background` isn't highlighted:

![image](https://user-images.githubusercontent.com/300146/130309072-d326e14d-6cd4-464f-a49d-f581a72c9f19.png)

This would be quite useful when editing theme files so that one can see colours "live" instead of bare variables:

![image](https://user-images.githubusercontent.com/300146/130309123-324f6149-1d83-46eb-95c8-125e5a45eefc.png)

**Comment by chrisbra** [comment]
I am sorry, this requires semantic understanding of Vim script. That is far out of scope for a simple colorizer I fear.
